### ISSUE TITLE
config example is not visible

### ISSUE THREAD

**Issue by yy** [akngs/ecogwiki#97]
In the README, there is a link to an example .config: http://www.ecogwiki.com/.config?_type=txt

However, this example page is not visible ("You don't have a permission").

**Comment by akngs** [comment]
Here's my `.config`:

```

.write jania902@gmail.com

    #!yaml
    navigation:
      - name: Home
        url: /Home
        shortcut: H
      - name: Posts
        url: /sp.posts
        shortcut: P
      - name: Changes
        url: /sp.changes
        shortcut: C
      - name: About
        url: /About
        style: "float: right"
    admin:
      email: jania902@gmail.com
      twitter: alankang
    service:
      domain: www.ecogwiki.com
      title: Ecogwiki
      ga_profile_id: UA-42871229-1
      google_oauth2_web_client_id: "959469477256-vc9g989vednfac2mfj8ieojo7r88pulp.apps.googleusercontent.com"
      google_drive_folder: "ecogwiki_public"
      css_list:
        - "/statics/css/base.css"
      default_permissions:
        read: [jania902@gmail.com]
        write: [jania902@gmail.com]
```

Please note that this project is not actively maintained. I don't recommend anyone to use it. I personally use mediawiki now. :(
